file_format: "1"
id: loprocosmos_central
name: LoPro Cosmos Central
type: shield
url: https://github.com/souzacef/LoPro_Cosmos
requires: [pro_micro]
features: []
siblings:
  - lopro_cosmos_left
  - lopro_cosmos_right
  
